/**
 * Onboarding for the controlled side of the fleet.
 *
 * The hard part of adding a machine is not this plugin's configuration — it is that the controlled
 * machine has to be prepared first (an SSH server listening, its firewall letting this controller in,
 * a DSH profile that speaks ACP, and this controller's PUBLIC key in the right account's
 * `authorized_keys`). That preparation cannot be automated from here: it needs one login the controller
 * does not yet have, which is the bootstrap circle.
 *
 * So it is turned into a single artifact the user can carry across by hand: one self-contained prompt,
 * generated here, pasted on the controlled machine. Only the PUBLIC key travels in it, so the private
 * key never leaves this machine and nothing sensitive ever has to come back.
 *
 * The prose lives in `./prompt-sections.js` as data; this module owns filling the variables, numbering
 * the steps, and embedding the key block.
 *
 * @module dsh-fleet/setup
 */
import { basename } from 'node:path';
import { homedir } from 'node:os';
import { ACCOUNT_KNOWN, ACCOUNT_UNKNOWN, FIREWALL_STEP, GOAL, KEY_STEP, PROFILE_STEP, REPORT, REPORTING_STEP, SSHD_STEP } from './prompt-sections.js';

/** Private keys this plugin will use without asking, in preference order. */
const CANDIDATE_KEYS = ['dsh_fleet_master_ed25519', 'dsh_master_ed25519', 'id_ed25519', 'id_rsa', 'id_ecdsa'];

/** Where a key generated by this plugin is written. */
export const GENERATED_KEY_NAME = 'dsh_fleet_master_ed25519';

/** The comment carried by a key this plugin generates, so it is recognizable in `authorized_keys`. */
export const GENERATED_KEY_COMMENT = 'dsh-fleet-master';

/** Join a home directory and an `.ssh` member, keeping the separator style the home path uses. */
function homePath(...segments) {
  const home = homedir();
  const separator = home.includes('\\') ? '\\' : '/';
  return [home.replace(/[\\/]+$/, ''), ...segments].join(separator);
}

/** The SSH directory assumed when the caller names none. */
export function defaultSshDir() {
  return homePath('.ssh');
}

/**
 * Whether a spawn failure means "this command does not exist" rather than "it ran and something else
 * went wrong".
 *
 * The error class lives in `@deepseek-ai/dsh-subprocess`, which a profile-installed plugin cannot resolve,
 * so the check is by name and message instead of by `instanceof`. Several signals are accepted because a
 * single one is fragile: the class name is not preserved if the error is re-wrapped, and `ENOENT` is what a
 * raw `child_process` spawn raises.
 *
 * @param error - the value thrown by the spawn seam.
 * @returns true when the command itself could not be resolved.
 */
function isExecutableNotFound(error) {
  if (typeof error !== 'object' || error === null) return false;
  if (error.constructor?.name === 'SubprocessExecutableNotFoundError') return true;
  if (error.name === 'SubprocessExecutableNotFoundError') return true;
  if (error.code === 'ENOENT') return true;
  return /was not found on PATH|was not found|command not found/i.test(String(error.message ?? ''));
}

/**
 * Which SSH tools exist on THIS machine — the controller.
 *
 * The plugin cannot do its job without them: `ssh` carries every delegation, and `ssh-keygen` reads and
 * creates the key that authenticates it. When one is missing the failure surfaces much later as a bare
 * spawn error that says nothing about what to install, so the environment is probed up front instead.
 *
 * Presence is decided by whether the binary STARTED, not by what it printed or which status it returned.
 * That keeps the answer correct for any client implementation, and it means no probe has to be a valid
 * invocation — important, because a bare `ssh-keygen` is not innocent: it starts generating a key pair.
 *
 * `ssh` is probed through the identity the operator configured, since an absolute path is exactly the
 * workaround for a PATH that cannot be trusted.
 *
 * @param deps - `{ subprocess }` seam.
 * @param options - `sshCommand` (default `ssh`).
 * @returns `{ ssh, keygen, ok, sshCommand }`; each tool is `{ command, present, detail }`.
 */
export async function inspectEnvironment(deps, options = {}) {
  const sshCommand = typeof options.sshCommand === 'string' && options.sshCommand !== '' ? options.sshCommand : 'ssh';
  const probe = async (command, argv) => {
    if (deps.subprocess === undefined) {
      return { command, present: false, detail: 'no subprocess service in this composition' };
    }
    const result = await runCollect((spec) => deps.subprocess.spawn(spec), {
      argv: [command, ...argv],
      cwd: homedir(),
      env: {},
      stdio: { stdin: 'ignore', stdout: 'pipe', stderr: 'pipe' },
    });
    if (!result.started) {
      return {
        command,
        present: false,
        detail: isExecutableNotFound(result.error) ? `not found: ${command}` : result.stderr.trim(),
      };
    }
    // It ran. What it printed is reported for the operator's benefit, and saying nothing is still "present".
    return { command, present: true, detail: `${result.stderr}${result.stdout}`.trim().split('\n')[0].trim() };
  };
  const ssh = await probe(sshCommand, ['-V']);
  const keygen = await probe('ssh-keygen', ['-?']);
  return { ssh, keygen, ok: ssh.present && keygen.present, sshCommand };
}

/**
 * The prompt a user pastes into a session on THIS machine to install what is missing.
 *
 * Same rule as the controlled-side prompt: state the goal and the criteria, leave the commands to the
 * agent that knows the platform. Installing an SSH client needs administrator rights on Windows and a
 * package manager elsewhere, both of which the local session can do and this plugin cannot.
 *
 * @param options - `{ ssh, keygen }` from {@link inspectEnvironment}.
 * @returns the prompt text.
 */
export function buildLocalSetupPrompt(options = {}) {
  const missing = [];
  if (options.ssh?.present !== true) missing.push('`ssh`（客户端）');
  if (options.keygen?.present !== true) missing.push('`ssh-keygen`（生成密钥）');
  const listed = missing.join('、');
  return [
    `本机（这台电脑）缺少 ${listed}。DSH 的跨机派活插件要用${missing.length > 1 ? '它们' : '它'}，请装好并确认可用。`,
    '',
    '要求：',
    '',
    '1. **只在这台电脑上操作**，与任何远程机器无关。',
    `2. 装上缺失的组件：${listed}。用你熟悉的方式（你知道自己是哪个系统、有哪些包管理器）。`,
    '3. 装完确认这两个命令都能执行并打印版本，把 `ssh -V` 和 `ssh-keygen` 的实际输出报给我。',
    '4. 如果装完仍然找不到命令，说明不在 PATH 里 —— 把两个可执行文件的**绝对路径**报给我，插件支持填绝对路径。',
    '',
    '需要管理员/提权的操作，直接做即可（这个会话已开启完全权限）。做完只需要回报上面第 3、4 条要求的内容。',
  ].join('\n');
}

/**
 * The part of a public key that actually identifies it.
 *
 * A key line is `[options] <type> <base64> [comment]`, and the COMMENT IS ARBITRARY: the key already
 * on a machine may carry the name of whatever tool created it. Deduplicating on a comment therefore
 * silently stops working the moment someone brings their own key — measured on a real machine, where
 * a marker-based guard appended the same key a second time. The type+base64 pair is the identity.
 *
 * @param publicKeyLine - one OpenSSH public key line.
 * @returns the identity, or the trimmed line when it does not parse.
 */
export function keyIdentityOf(publicKeyLine) {
  const trimmed = String(publicKeyLine).trim();
  const match = /^(?:[^\s]+\s+)*?(ssh-[A-Za-z0-9@.-]+|ecdsa-[A-Za-z0-9@.-]+|sk-[A-Za-z0-9@.-]+)\s+([A-Za-z0-9+/=]+)/.exec(trimmed);
  return match === null ? trimmed : `${match[1]} ${match[2]}`;
}

/** The platform-correct display form of a path (forward slashes for ssh, backslashes for Windows). */
function keyPathForSsh(path) {
  return path.replace(/\\/g, '/');
}

/**
 * Where a generated key would live, and whether one is already there.
 *
 * @param options - `sshDir` overrides the default `~/.ssh`.
 * @returns `{ sshDir, privateKey, publicKey, exists }`.
 */
export function generatedKeyPaths(options = {}) {
  const sshDir = typeof options.sshDir === 'string' && options.sshDir !== '' ? options.sshDir : defaultSshDir();
  // `name` lets a replacement key be written beside the original instead of over it.
  const name = typeof options.name === 'string' && options.name !== '' ? options.name : GENERATED_KEY_NAME;
  const separator = sshDir.includes('\\') ? '\\' : '/';
  return {
    sshDir,
    privateKey: `${sshDir}${separator}${name}`,
    publicKey: `${sshDir}${separator}${name}.pub`,
  };
}

/** The `.pub` path beside a private key, in the style the private key path already uses. */
export function publicKeyPathOf(privateKey) {
  return `${privateKey}.pub`;
}

/** A one-line fingerprint of an OpenSSH public key, so both sides can compare without showing it. */
export function fingerprintOf(publicKeyLine) {
  const trimmed = String(publicKeyLine).trim();
  if (trimmed === '') return '';
  let hash = 5381;
  for (let index = 0; index < trimmed.length; index += 1) {
    hash = ((hash * 33) ^ trimmed.charCodeAt(index)) >>> 0;
  }
  return `dsh-fleet-${hash.toString(16).padStart(8, '0')}`;
}

/** The subprocess seam requires a positive finite teardown grace; short-lived commands need little. */
const COMMAND_GRACE_MS = 3000;

/**
 * Run one short-lived command through the subprocess seam and collect everything it printed.
 *
 * Exported for the session-prune feature, which runs `ssh` directly rather than through the ACP driver: the
 * prune temporarily STOPS the app on the far side, so it cannot use the ACP channel it is cleaning up after.
 * The spawn/collect semantics below are the ones already proven by the setup probes, so they live in one
 * place instead of being re-derived.
 *
 * @param spawn - the subprocess provider's `spawn`.
 * @param argv - the argv to run.
 * @returns `{ started, code, stdout, stderr }`; `started: false` means it never launched.
 */
export async function runCommandCollect(spawn, argv) {
  return await runCollect(spawn, {
    argv,
    cwd: homedir(),
    env: {},
    stdio: { stdin: 'ignore', stdout: 'pipe', stderr: 'pipe' },
  });
}

/**
 * Run one short-lived command and collect its output.
 *
 * The subprocess handle exposes `stdout`/`stderr` as async iterables, `done` for the exit facts, and
 * `terminate()` for teardown — the same members the ACP driver relies on.
 *
 * `started` distinguishes the two ways this can fail, and the distinction matters: a command that never
 * launched is a missing tool, while one that launched and exited non-zero is a command that ran and
 * disagreed. Collapsing both into a non-zero code is what made "OpenSSH is not installed" indistinguishable
 * from "ssh-keygen refused this file".
 *
 * @param spawn - the subprocess seam.
 * @param spec - the process spec.
 * @returns `{ started, code, stdout, stderr }`.
 */
async function runCollect(spawn, spec) {
  let child;
  try {
    // The provider rejects a spec without a positive finite `graceMs` before it ever spawns.
    child = spawn({ graceMs: COMMAND_GRACE_MS, ...spec });
  } catch (error) {
    return { started: false, code: -1, stdout: '', stderr: String(error?.message ?? error), error };
  }
  const settled = Promise.resolve(child.done).then(
    (outcome) => ({ ok: true, outcome }),
    (error) => ({ ok: false, error }),
  );
  const chunks = [];
  let stderr = '';
  const readers = [];
  if (child.stdout !== undefined) {
    readers.push((async () => {
      for await (const chunk of child.stdout) chunks.push(Buffer.from(chunk));
    })());
  }
  if (child.stderr !== undefined) {
    readers.push((async () => {
      for await (const chunk of child.stderr) stderr += Buffer.from(chunk).toString('utf8');
    })());
  }
  try {
    await Promise.all(readers);
  } catch (error) {
    stderr += `${stderr === '' ? '' : '\n'}reading the child stream failed: ${String(error?.message ?? error)}`;
  }
  const exit = await settled;
  const outcome = exit.ok ? exit.outcome : undefined;
  const code = typeof outcome?.exitCode === 'number' ? outcome.exitCode : (exit.ok ? 0 : -1);
  if (!exit.ok) stderr += `${stderr === '' ? '' : '\n'}${String(exit.error?.message ?? exit.error)}`;
  try {
    child.terminate();
  } catch {
    // Already gone.
  }
  return { started: true, code, stdout: Buffer.concat(chunks).toString('utf8'), stderr };
}

/**
 * List the private keys this controller could offer.
 *
 * The client half has no file picker, so "change key" has to be a choice among keys that actually exist
 * here. Every key named in {@link CANDIDATE_KEYS} is reported first, then any other plausible private key
 * in the same directory, so a key with a custom name is still selectable.
 *
 * Read-only, and deliberately tolerant: an unreadable directory yields an empty list rather than an
 * error, because "you have no keys yet" is a normal state that the panel renders as a call to action.
 *
 * @param deps - `{ fs }` seam; defaults to `node:fs/promises`.
 * @param options - `sshDir`.
 * @returns `{ sshDir, keys: [{ path, name, hasPublicHalf }] }`.
 */
export async function listPrivateKeys(deps = {}, options = {}) {
  const fs = deps.fs ?? (await import('node:fs/promises'));
  const sshDir = typeof options.sshDir === 'string' && options.sshDir !== '' ? options.sshDir : defaultSshDir();
  const separator = sshDir.includes('\\') ? '\\' : '/';
  const join = (name) => `${sshDir}${separator}${name}`;

  let entries = [];
  try {
    entries = await fs.readdir(sshDir);
  } catch {
    return { sshDir, keys: [] };
  }

  // Names that are never a usable private key.
  const skip = new Set(['authorized_keys', 'known_hosts', 'known_hosts.old', 'config', 'environment']);
  const present = new Set(entries.filter((name) => !name.endsWith('.pub') && !skip.has(name) && !name.startsWith('.')));

  const ordered = [
    ...CANDIDATE_KEYS.filter((name) => present.has(name)),
    ...[...present].filter((name) => !CANDIDATE_KEYS.includes(name)).sort(),
  ];

  const keys = [];
  for (const name of ordered) {
    const path = join(name);
    let hasPublicHalf = false;
    try {
      await fs.access(`${path}.pub`);
      hasPublicHalf = true;
    } catch {
      // The public half can still be derived with ssh-keygen; report it as absent rather than unknown.
    }
    keys.push({ path, name, hasPublicHalf });
  }
  return { sshDir, keys };
}

/**
 * Find the private key this plugin should use, or report that one must be generated.
 *
 * Read-only: it never creates anything. Generation is a separate, explicitly approved call.
 *
 * @param deps - `{ subprocess, fs }` seams; `fs` defaults to `node:fs/promises`.
 * @param options - `sshDir`, `preferredKey` (a configured `keyFile`).
 * @returns `{ candidates, preferred, sshDir, generated }`.
 */
export async function resolveKey(deps, options = {}) {
  const fs = deps.fs ?? (await import('node:fs/promises'));
  const sshDir = typeof options.sshDir === 'string' && options.sshDir !== '' ? options.sshDir : defaultSshDir();
  const paths = generatedKeyPaths({ sshDir });
  const candidates = [];
  for (const name of CANDIDATE_KEYS) {
    const privateKey = `${sshDir}${sshDir.includes('\\') ? '\\' : '/'}${name}`;
    try {
      await fs.access(privateKey);
      candidates.push(privateKey);
    } catch {
      // Not present; the next candidate is tried.
    }
  }
  const preferred = typeof options.preferredKey === 'string' && options.preferredKey !== '' ? options.preferredKey : undefined;
  // Reported separately because the two failures need different sentences. A NAMED key that is not there is a
  // typo in the settings, and it must not be papered over: the caller would otherwise fall back to one of the
  // scanned names and offer a prompt signed by a key the operator did not choose.
  let preferredExists = false;
  if (preferred !== undefined) {
    try {
      await fs.access(preferred);
      preferredExists = true;
    } catch {
      preferredExists = false;
    }
  }
  return {
    sshDir,
    preferred,
    preferredExists,
    candidates,
    generated: {
      ...paths,
      exists: candidates.includes(paths.privateKey),
    },
  };
}

/**
 * Read the PUBLIC half of a key pair, without ever reading the private key.
 *
 * An existing `.pub` is used as-is; when only the private key is present, `ssh-keygen -y` derives the
 * public half. The private key's bytes are never returned, logged, or embedded anywhere.
 *
 * @param deps - `{ subprocess }` seam.
 * @param privateKey - path to the private key.
 * @returns `{ publicKey, fingerprint, source }`, or `{ problem }` when it cannot be determined.
 */
export async function readPublicKey(deps, privateKey) {
  const fs = deps.fs ?? (await import('node:fs/promises'));
  const publicKey = publicKeyPathOf(privateKey);
  try {
    const text = (await fs.readFile(publicKey, 'utf8')).trim();
    if (text !== '') return { publicKey: text, fingerprint: fingerprintOf(text), source: 'public-file' };
  } catch {
    // No .pub beside it; fall through to deriving it.
  }
  if (deps.subprocess === undefined) {
    return { problem: `no ${basename(publicKey)} beside it, and this composition provides no subprocess service to derive it ／ 它旁边没有 ${basename(publicKey)}，而这个组合也没有提供 subprocess 服务来推导它` };
  }
  try {
    const result = await runCollect((spec) => deps.subprocess.spawn(spec), {
      argv: ['ssh-keygen', '-y', '-f', keyPathForSsh(privateKey)],
      cwd: homedir(),
      env: {},
      stdio: { stdin: 'ignore', stdout: 'pipe', stderr: 'pipe' },
    });
    const text = result.stdout.trim();
    if (result.code === 0 && text !== '') return { publicKey: text, fingerprint: fingerprintOf(text), source: 'derived' };
    return { problem: `ssh-keygen could not derive the public key (exit ${String(result.code)}): ${result.stderr.trim() || 'no diagnostic'} ／ ssh-keygen 无法推导出公钥（退出码 ${String(result.code)}）：${result.stderr.trim() || '没有诊断信息'}` };
  } catch (error) {
    return { problem: `ssh-keygen could not be started: ${String(error?.message ?? error)} ／ ssh-keygen 无法启动：${String(error?.message ?? error)}` };
  }
}

/**
 * Generate the controller's key pair.
 *
 * Called only after the user approves it, because it writes outside the workspace. The passphrase is
 * empty on purpose: these delegations run unattended, so a passphrase-protected key could not be
 * used without an agent.
 *
 * An existing key is NEVER overwritten. `ssh-keygen` would otherwise stop at an interactive
 * `Overwrite (y/n)?` prompt that nothing can answer, and a stray key must not be destroyed by a
 * convenience button.
 *
 * @param deps - `{ subprocess }` seam.
 * @param options - `sshDir`.
 * @returns `{ privateKey, publicKey, fingerprint }`, or `{ problem }`.
 */
/**
 * Generate a fresh controller key pair.
 *
 * The rule is one sentence: use the base name when it is free, otherwise write a NEW pair beside it under
 * a dated name. Overwriting is never an option — the previous PRIVATE key is disposable, but the previous
 * PUBLIC key is installed on machines that were prepared with it, so destroying it would lock the operator
 * out of those machines. Keeping it costs one file and preserves that access.
 *
 * Whatever the caller means by "generate a key" — first key, or a replacement — this produces a new pair
 * and never touches an existing one. `ssh-keygen` is never pointed at a path that exists, because it would
 * then stop at an interactive overwrite prompt.
 *
 * @param deps - `{ subprocess, fs }` seams.
 * @param options - `sshDir`.
 * @returns `{ privateKey, publicKey, sshDir, fingerprint, replaced? }` or `{ problem }`.
 */
export async function generateKey(deps, options = {}) {
  if (deps.subprocess === undefined) return { problem: 'this composition provides no subprocess service, so no key can be generated ／ 这个组合没有提供 subprocess 服务，因此无法生成密钥' };
  const base = generatedKeyPaths(options);
  const fs = deps.fs ?? (await import('node:fs/promises'));
  try {
    await fs.mkdir(base.sshDir, { recursive: true, mode: 0o700 });
  } catch (error) {
    return { problem: `cannot create ${base.sshDir}: ${String(error?.message ?? error)} ／ 无法创建 ${base.sshDir}：${String(error?.message ?? error)}` };
  }

  const taken = async (path) => {
    try {
      await fs.access(path);
      return true;
    } catch {
      return false;
    }
  };

  if (!(await taken(base.privateKey))) return generateInto(deps, base);

  // Dated, then numbered if the day already has one, so repeated generations each keep their own file.
  const stamp = new Date().toISOString().slice(0, 10);
  for (let attempt = 0; attempt < 100; attempt += 1) {
    const suffix = attempt === 0 ? stamp : `${stamp}_${String(attempt + 1)}`;
    const candidate = generatedKeyPaths({ ...options, name: `${GENERATED_KEY_NAME}_${suffix}` });
    if (await taken(candidate.privateKey)) continue;
    const made = await generateInto(deps, candidate);
    if (made.problem !== undefined) return made;
    return { ...made, replaced: base.privateKey };
  }
  return { problem: `cannot find a free key name beside ${base.privateKey} ／ 在 ${base.privateKey} 旁边找不到可用的密钥文件名` };
}

/**
 * Generate one key pair at an exact, known-free location.
 *
 * @param deps - `{ subprocess, fs }` seams.
 * @param paths - the private/public paths to write.
 * @returns the generated key facts, or `{ problem }`.
 */
async function generateInto(deps, paths) {
  try {
    const result = await runCollect((spec) => deps.subprocess.spawn(spec), {
      argv: [
        'ssh-keygen', '-t', 'ed25519', '-N', '', '-C', GENERATED_KEY_COMMENT,
        '-f', keyPathForSsh(paths.privateKey),
      ],
      cwd: paths.sshDir,
      env: {},
      stdio: { stdin: 'ignore', stdout: 'pipe', stderr: 'pipe' },
    });
    if (result.code !== 0) {
      return { problem: `ssh-keygen failed (exit ${String(result.code)}): ${result.stderr.trim() || result.stdout.trim()} ／ ssh-keygen 执行失败（退出码 ${String(result.code)}）：${result.stderr.trim() || result.stdout.trim()}` };
    }
  } catch (error) {
    return { problem: `ssh-keygen could not be started: ${String(error?.message ?? error)} ／ ssh-keygen 无法启动：${String(error?.message ?? error)}` };
  }
  const read = await readPublicKey(deps, paths.privateKey);
  if (read.problem !== undefined) return read;
  return { ...paths, publicKey: read.publicKey, fingerprint: read.fingerprint };
}

// ── prompt construction ────────────────────────────────────────────────────────────────────────

/**
 * The two rules that must appear verbatim in every prompt, exported so tests can assert on the
 * canonical text instead of a copy of it that drifts.
 */


/**
 * Build the controlled-side prompt.
 *
 * The prose is data (`./prompt-sections.js`); this function only fills variables, numbers the steps, and
 * embeds the one block that must be byte-exact — the public key.
 *
 * @param options - `{ publicKey, user, host, port }`. The port is the one the controller will actually
 *   connect to, so the prompt never hardcodes 22.
 * @returns the prompt text.
 */
export function buildSetupPrompt(options) {
  const publicKey = String(options.publicKey ?? '').trim();
  const user = String(options.user ?? '').trim();
  const host = String(options.host ?? '').trim();
  // An account is OPTIONAL, and its absence is not a failure. The account lives on the controlled machine, and
  // the prompt already sends that machine to find it and report back — so requiring the controller to name it
  // first was the controller demanding information only the other side can supply. When it IS known, the step
  // reads as "verify this claim"; when it is not, the step reads as "find out, then report".
  //
  // What is NOT acceptable is a fabricated value in its place. A literal `<the controller's account>` reached a
  // real machine once and its agent did the sensible thing — it stopped and asked — which is a wasted round trip
  // and indistinguishable from a value somebody actually typed.
  const accountKnown = user !== '';
  const controller = accountKnown ? user : '本机实际的账号';
  // The panel's form gives every field as a string, so accept a numeric string too. Defaulting to 22
  // matches the machine-record default; an explicit port always wins.
  const requestedPort = Number.parseInt(String(options.port ?? ''), 10);
  const port = Number.isInteger(requestedPort) && requestedPort > 0 && requestedPort <= 65535
    ? String(requestedPort)
    : '22';

  // One substitution for every section, so a placeholder can never survive in one of them while being
  // filled in the others. That exact slip shipped once: the opening line still read `{CONTROLLER}`
  // while the steps below it carried the real name.
  const fill = (text) => text
    .replaceAll('{CONTROLLER}', controller)
    .replaceAll('{HOST}', host)
    .replaceAll('{PORT}', port)
    .replaceAll('{PUBLIC_KEY}', publicKey)
    .replaceAll('{KEY_IDENTITY}', keyIdentityOf(publicKey))
    // The controller's own address, for the machine to compare subnets against and to ping. Empty when there is
    // no callback — the copied prompt has no controller address to offer, and the address rule then falls back
    // to the exclusion list alone rather than naming a target it does not have.
    .replaceAll('{CALLBACK_HOST}', typeof options.callback?.address === 'string' ? options.callback.address : '');

  // The account paragraph is chosen here and substituted BEFORE `fill` runs, so the paragraph's own
  // `{CONTROLLER}` is resolved by the same pass. The other order would leave a literal `{CONTROLLER}` inside
  // the step — the exact class of bug the comment above records.
  const accountStep = accountKnown ? ACCOUNT_KNOWN : ACCOUNT_UNKNOWN;
  const step = (index, text) => fill(text.replace('{ACCOUNT_STEP}', accountStep))
    .replace(/^## /, `## 步骤 ${String(index + 1)}：`);

  // The reporting section exists only for the SERVED prompt: it names an address to report to, and a copied
  // prompt has none. Telling a machine to report into nowhere would be worse than saying nothing.
  const reporting = typeof options.callback?.url === 'string' && options.callback.url !== ''
    ? `${fill(REPORTING_STEP
      .replaceAll('{CALLBACK_URL}', options.callback.url)
      .replaceAll('{CALLBACK_TOKEN}', String(options.callback.token ?? '')))}\n\n`
    : '';

  return [
    fill(GOAL),
    '',
    reporting + step(0, SSHD_STEP),
    '',
    step(1, FIREWALL_STEP),
    '',
    step(2, PROFILE_STEP),
    '',
    step(3, KEY_STEP),
    '',
    fill(REPORT),
    '',
  ].join('\n');
}
/**
 * Assemble the onboarding answer: which key is on offer, and the prompt to carry across.
 *
 * @param deps - `{ subprocess, fs? }` seams.
 * @param options - `{ user, host, port, keyFile, sshDir }`. `port` defaults to the machine default when
 *   omitted, so the prompt still names a concrete port.
 * @returns `{ keyFile, keySource, fingerprint, prompt }`, or `{ problem, hint? }` when no key can be
 *   offered.
 */
export async function buildSetup(deps, options = {}) {
  const resolved = await resolveKey(deps, { sshDir: options.sshDir, preferredKey: options.keyFile });
  // A key the operator NAMED but that is not on disk is its own problem, not a reason to quietly use a
  // different one. Falling through to the scanned names would emit a prompt carrying a public key the operator
  // never chose — and the machine would then authorize that key. Say it instead.
  if (resolved.preferred !== undefined && resolved.preferredExists === false) {
    return {
      needs: 'key',
      problem: `the key named in the settings is not there: ${resolved.preferred} ／ 设置里指定的密钥不存在：${resolved.preferred}`,
      hint: 'Correct the key path in the shared settings, or clear it to let this page pick a key from your SSH directory. ／ 改正共享设置里的密钥路径，或者清空它、让本页从你的 SSH 目录里挑一把。',
      sshDir: resolved.sshDir,
      candidates: resolved.candidates,
    };
  }
  const candidates = [...new Set([
    ...(resolved.preferred === undefined ? [] : [resolved.preferred]),
    ...resolved.candidates,
  ])];
  if (candidates.length === 0) {
    const paths = generatedKeyPaths({ sshDir: resolved.sshDir });
    return {
      // `needs` is a discriminator, not decoration. This outcome and "the account is missing" are both a
      // `problem`, and the panel rendered ONE fixed message for either — telling an operator who had no key
      // problem at all that they had no key, beside a button that generates one. The panel now picks its
      // wording and its remedy from this value.
      needs: 'key',
      problem: 'this controller has no SSH key to offer ／ 这台主控机没有可用的 SSH 密钥',
      hint: `Generate one with a separate, approved step (ssh-keygen -t ed25519 -N "" -C ${GENERATED_KEY_COMMENT} -f ${paths.privateKey}), or name an existing private key in \`keyFile\`. ／ 用一个单独且已获批准的步骤生成一把（ssh-keygen -t ed25519 -N "" -C ${GENERATED_KEY_COMMENT} -f ${paths.privateKey}），或者在 \`keyFile\` 里指定一个已有的私钥。`,
      sshDir: resolved.sshDir,
      candidates,
      generated: paths,
    };
  }
  const privateKey = candidates[0];
  const read = await readPublicKey(deps, privateKey);
  if (read.problem !== undefined) return { needs: 'key-unreadable', problem: `cannot read the public half of ${privateKey}: ${read.problem} ／ 无法读取 ${privateKey} 的公钥部分：${read.problem}`, privateKey };
  // No `needs: 'user'` outcome exists. An account is optional, and its absence is not a failure: the account
  // lives on the controlled machine, the prompt sends that machine to find it, and the answer comes back in the
  // report step. Requiring it here was the controller demanding information only the other side can supply —
  // and it broke the one workflow that never needed it, a machine set up before it has been added.
  const prompt = buildSetupPrompt({ publicKey: read.publicKey, user: options.user, host: options.host, port: options.port, callback: options.callback });
  return {
    keyFile: keyPathForSsh(privateKey),
    keySource: read.source,
    // Reported so the CONTROLLER can recognize the key; the prompt deliberately asks the controlled
    // machine for the standard SSH fingerprint instead, since it cannot compute this one.
    fingerprint: read.fingerprint,
    prompt,
  };
}
